version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5505:5432
    volumes:
      - ~/apps/takshashila-backend:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=takshashila
